name: Test Revision
on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:            
          - name: Windows 64
            os: windows-latest
            args: --os=win64 --cpu=x86_64
            
          - name: Windows 32  
            os: windows-latest
            args: --os=win32 --cpu=i386

          - name: Linux 64
            os: ubuntu-latest
            args: --os=linux --cpu=x86_64
            
          - name: Linux (aarch64)  
            os: ubuntu-latest
            args: --os=linux --cpu=aarch64
            
          - name: MacOS 64
            os: macos-latest
            args: --os=darwin --cpu=x86_64 --widgetset=cocoa
 
          - name: MacOS (aarch64)
            os: macos-latest
            args: --os=darwin --cpu=aarch64 --widgetset=cocoa 
            
    steps:
      - uses: actions/checkout@v3.1.0    
      - name: Install Lazarus
        uses: ./
        with:
          laz: 537f43754ca77e39f15839299b9f7059e39f90dd
          fpc: 3f7bf0fd70b339a43889898efa59af4fec33ea84
      
      - name: Build Test
        run: |
          lazbuild ${{ matrix.config.args }} test_lazarus.lpi
          
      - name: Run Test
        if: matrix.config.name != 'Linux (aarch64)' && matrix.config.name != 'MacOS (aarch64)' # cross compiled
        run: |
          ./test
